// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX3EUmtQgRXrZBJl6vczu9oMPzM-51uNU',
    appId: '1:768520685499:web:adfdaa9a3c293fe9c0269e',
    messagingSenderId: '768520685499',
    projectId: 'fitness-app-assignment',
    authDomain: 'fitness-app-assignment.firebaseapp.com',
    storageBucket: 'fitness-app-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEaMPUI7ZfbGiws2_vOdPgvOqqZXCea2Y',
    appId: '1:768520685499:android:a3a76a747bab1bbac0269e',
    messagingSenderId: '768520685499',
    projectId: 'fitness-app-assignment',
    storageBucket: 'fitness-app-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQLg2Ue7lkrPMfhzdcnrKWUoLmwq-LbNc',
    appId: '1:768520685499:ios:5b011ee3420d7713c0269e',
    messagingSenderId: '768520685499',
    projectId: 'fitness-app-assignment',
    storageBucket: 'fitness-app-assignment.appspot.com',
    iosClientId: '768520685499-stji22t0qrhe88m09jtia85516ahb9f4.apps.googleusercontent.com',
    iosBundleId: 'com.nurettinselim.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQLg2Ue7lkrPMfhzdcnrKWUoLmwq-LbNc',
    appId: '1:768520685499:ios:5b011ee3420d7713c0269e',
    messagingSenderId: '768520685499',
    projectId: 'fitness-app-assignment',
    storageBucket: 'fitness-app-assignment.appspot.com',
    iosClientId: '768520685499-stji22t0qrhe88m09jtia85516ahb9f4.apps.googleusercontent.com',
    iosBundleId: 'com.nurettinselim.fitnessApp',
  );
}
